### ISSUE TITLE
Easy way to check the build

### ISSUE THREAD

**Issue by dbooth-boston** [mappinghub/views#6]
Is there an easy way to check the build?  If so, it would be good to mention it from the developer documentation.  The purpose is to allow a user to verify that their contributions work before pushing them.

**Comment by dmtaub** [comment]
The build status is visible in the readme on GitHub. Checking a log is more
difficult

**Comment by dbooth-boston** [comment]
Actually I meant locally check the build, so that someone can verify that everything works before pushing.

**Comment by dmtaub** [comment]
Other than running "npm run build" you mean?

**Comment by dbooth-boston** [comment]
No, that sounds like a perfect way.  Let's put that in the user documentation.  I'll assign this one to Glenna, since she is doing the user documentation.

**Comment by dmtaub** [comment]
Recent changes allow running "npm run build" without overwriting the README and index.html files

**Comment by dmtaub** [comment]
added to the Readme.md
