### ISSUE TITLE
Views build fails with node.js v6.x

### ISSUE THREAD

**Issue by dbooth-boston** [mappinghub/views#8]
Nash: The local build of mapping hub views worked after I downgraded my node installation to 4.8.0 (the build had issues on node 6x)

**Comment by dmtaub** [comment]
This is known, I had originally designed for node 6, but Glenna's script
was designed for 4 for ease of development. Thus, I switched Travis to
install node 4 instead (visible in .travis.yml). Aside from that script,
everything else should work in six.
